In [1]:
import glob
import pickle
import matplotlib.pyplot as plt
import os

In [23]:
import pandas as pd
import numpy as np

In [59]:
def compile_attributes(model="iwae", dataset="mnist_perturbed"):
    count = 0
    all_attributes = []
    for filename in sorted(glob.glob(os.path.join(model, dataset, "-1", "*", "attributes.pk"))):
        with open(filename, "rb") as f:
            attributes = pickle.load(f)
            all_attributes.append(attributes)
    for i, fn in enumerate(sorted(glob.glob(os.path.join(model, dataset, "-1", "*", "attributes.pk")))):
        print(i, fn)
    print("Found {} attributes".format(len(all_attributes)))
    cols = ['nz',  'nnodes_recog', 'nnodes_gener', 'num_weights', 'wall_time', 'test_ll', 'test_curve', 'max_validation']
    df = pd.DataFrame(columns=cols)
    for i, att in enumerate(all_attributes):
#         print(len(att["test_curve"]) - np.argmax(att["test_curve"]))
        att["test_curve"] = att["test_curve"][-12]
        if att["test_curve"] > att["test_ll"]:
            count+=1
        row = [att[c] for c in cols]
        df.loc[i] = row
    print(count)
    return df

In [60]:
df = compile_attributes("iwae", "mnist_perturbed")
df.sort_values("max_validation", ascending=False)

0 iwae/mnist_perturbed/-1/1557238098/attributes.pk
1 iwae/mnist_perturbed/-1/1557238305/attributes.pk
2 iwae/mnist_perturbed/-1/1557238597/attributes.pk
3 iwae/mnist_perturbed/-1/1557239061/attributes.pk
4 iwae/mnist_perturbed/-1/1557239389/attributes.pk
5 iwae/mnist_perturbed/-1/1557239948/attributes.pk
6 iwae/mnist_perturbed/-1/1557240460/attributes.pk
7 iwae/mnist_perturbed/-1/1557240946/attributes.pk
8 iwae/mnist_perturbed/-1/1557241637/attributes.pk
9 iwae/mnist_perturbed/-1/1557241843/attributes.pk
10 iwae/mnist_perturbed/-1/1557242015/attributes.pk
11 iwae/mnist_perturbed/-1/1557242246/attributes.pk
12 iwae/mnist_perturbed/-1/1557242602/attributes.pk
13 iwae/mnist_perturbed/-1/1557243022/attributes.pk
14 iwae/mnist_perturbed/-1/1557243458/attributes.pk
15 iwae/mnist_perturbed/-1/1557243858/attributes.pk
16 iwae/mnist_perturbed/-1/1557244164/attributes.pk
17 iwae/mnist_perturbed/-1/1557244313/attributes.pk
18 iwae/mnist_perturbed/-1/1557244438/attributes.pk
19 iwae/mnist_perturbed/-1/1557244567/attributes.pk
20 iwae/mnist_perturbed/-1/1557244765/attributes.pk
21 iwae/mnist_perturbed/-1/1557244961/attributes.pk
22 iwae/mnist_perturbed/-1/1557245186/attributes.pk
23 iwae/mnist_perturbed/-1/1557245411/attributes.pk
24 iwae/mnist_perturbed/-1/1557245641/attributes.pk
25 iwae/mnist_perturbed/-1/1557245735/attributes.pk
26 iwae/mnist_perturbed/-1/1557245802/attributes.pk
27 iwae/mnist_perturbed/-1/1557245945/attributes.pk
28 iwae/mnist_perturbed/-1/1557246128/attributes.pk
29 iwae/mnist_perturbed/-1/1557246316/attributes.pk
30 iwae/mnist_perturbed/-1/1557246564/attributes.pk
31 iwae/mnist_perturbed/-1/1557246768/attributes.pk
Found 32 attributes
12

,nz,nnodes_recog,nnodes_gener,num_weights,wall_time,test_ll,test_curve,max_validation
23,200,"(300, 300)","(300, 300)",1545168,227.409601688385,2470.518066,2469.597412,2453.149902
21,100,"(300, 300)","(300, 300)",1424968,222.41999888420105,2476.627930,2478.148682,2452.877930
22,150,"(300, 300)","(300, 300)",1485068,223.14229440689087,2484.164062,2483.992920,2447.897217
29,100,"(600, 600)","(600, 600)",3568168,245.19338870048523,2470.053955,2467.695801,2441.920166
20,50,"(300, 300)","(300, 300)",1364868,193.75160145759583,2457.303955,2457.626709,2435.064697
30,150,"(600, 600)","(600, 600)",3688268,200.98993968963623,2455.946289,2457.894287,2428.989258
28,50,"(600, 600)","(600, 600)",3448068,186.0103940963745,2456.490479,2458.206787,2428.691162
31,200,"(600, 600)","(600, 600)",3808368,212.14317083358765,2450.162598,2451.383545,2423.843994
13,100,"(100, 100)","(100, 100)",396168,433.92971181869507,2432.518311,2431.950439,2397.705566
19,25,"(300, 300)","(300, 300)",1334818,195.24380111694336,2419.804688,2418.132324,2395.132080
12,50,"(100, 100)","(100, 100)",376068,416.82009291648865,2419.054688,2419.594482,2393.577393
27,25,"(600, 600)","(600, 600)",3388018,180.74788522720337,2406.483887,2404.359131,2393.319824
14,150,"(100, 100)","(100, 100)",416268,397.3323588371277,2419.124512,2419.468506,2390.193604
15,200,"(100, 100)","(100, 100)",436368,303.9510066509247,2399.022705,2397.382812,2372.870605
11,25,"(100, 100)","(100, 100)",366018,354.25705099105835,2360.836914,2359.321289,2340.749512
26,5,"(600, 600)","(600, 600)",3339978,140.7256727218628,2150.931641,2146.883789,2134.172607
7,200,"(30, 30)","(30, 30)",123888,688.9595110416412,2113.421143,2122.917725,2127.937256
4,50,"(30, 30)","(30, 30)",105588,556.6258924007416,2136.326904,2134.723145,2118.258301
5,100,"(30, 30)","(30, 30)",111688,509.5097315311432,2135.751953,2136.355225,2106.575195
6,150,"(30, 30)","(30, 30)",117788,483.29554653167725,2121.602295,2119.872070,2105.035156
18,5,"(300, 300)","(300, 300)",1310778,126.71474981307983,2118.614014,2119.443115,2101.214355
10,5,"(100, 100)","(100, 100)",357978,228.2865493297577,2104.107666,2103.716309,2079.354248
3,25,"(30, 30)","(30, 30)",102538,325.9804034233093,2046.972412,2045.067993,2039.986206
2,5,"(30, 30)","(30, 30)",100098,460.99668407440186,1999.151611,1998.482178,1978.408447
17,2,"(300, 300)","(300, 300)",1307172,122.52294397354126,1886.094360,1874.919189,1866.290405
9,2,"(100, 100)","(100, 100)",356772,169.7228388786316,1834.522827,1833.515747,1798.298828
1,2,"(30, 30)","(30, 30)",99732,290.03120827674866,1751.649170,1755.449585,1744.993408
16,1,"(300, 300)","(300, 300)",1305970,146.91297149658203,1681.864746,1673.584229,1661.485718
8,1,"(100, 100)","(100, 100)",356370,203.03885102272034,1653.744141,1651.067505,1636.164185
25,2,"(600, 600)","(600, 600)",3332772,64.03697609901428,1578.202515,1577.458740,1569.212769
0,1,"(30, 30)","(30, 30)",99610,200.22123074531555,1581.959839,1582.654785,1549.489380
24,1,"(600, 600)","(600, 600)",3330370,92.25804686546326,1425.478516,1422.642456,1419.235596

In [61]:
df = compile_attributes("iwae", "mnist_discrete")
df.sort_values("max_validation", ascending=False)

0 iwae/mnist_discrete/-1/1557246982/attributes.pk
1 iwae/mnist_discrete/-1/1557247478/attributes.pk
2 iwae/mnist_discrete/-1/1557247847/attributes.pk
3 iwae/mnist_discrete/-1/1557248277/attributes.pk
4 iwae/mnist_discrete/-1/1557248785/attributes.pk
5 iwae/mnist_discrete/-1/1557249360/attributes.pk
6 iwae/mnist_discrete/-1/1557249815/attributes.pk
7 iwae/mnist_discrete/-1/1557250324/attributes.pk
8 iwae/mnist_discrete/-1/1557250814/attributes.pk
9 iwae/mnist_discrete/-1/1557251097/attributes.pk
10 iwae/mnist_discrete/-1/1557251320/attributes.pk
11 iwae/mnist_discrete/-1/1557251562/attributes.pk
12 iwae/mnist_discrete/-1/1557251952/attributes.pk
13 iwae/mnist_discrete/-1/1557252269/attributes.pk
14 iwae/mnist_discrete/-1/1557252614/attributes.pk
15 iwae/mnist_discrete/-1/1557252887/attributes.pk
16 iwae/mnist_discrete/-1/1557253215/attributes.pk
17 iwae/mnist_discrete/-1/1557253430/attributes.pk
18 iwae/mnist_discrete/-1/1557253588/attributes.pk
19 iwae/mnist_discrete/-1/1557253734/attributes.pk
20 iwae/mnist_discrete/-1/1557253915/attributes.pk
21 iwae/mnist_discrete/-1/1557254106/attributes.pk
22 iwae/mnist_discrete/-1/1557254349/attributes.pk
23 iwae/mnist_discrete/-1/1557254536/attributes.pk
24 iwae/mnist_discrete/-1/1557254772/attributes.pk
25 iwae/mnist_discrete/-1/1557254996/attributes.pk
26 iwae/mnist_discrete/-1/1557255146/attributes.pk
27 iwae/mnist_discrete/-1/1557255282/attributes.pk
28 iwae/mnist_discrete/-1/1557255413/attributes.pk
29 iwae/mnist_discrete/-1/1557255594/attributes.pk
30 iwae/mnist_discrete/-1/1557255744/attributes.pk
31 iwae/mnist_discrete/-1/1557255913/attributes.pk
Found 32 attributes
21

,nz,nnodes_recog,nnodes_gener,num_weights,wall_time,test_ll,test_curve,max_validation
23,200,"(300, 300)","(300, 300)",1158584,233.1312382221222,-2629.138916,-2629.000977,-2672.475586
21,100,"(300, 300)","(300, 300)",1068384,241.54960012435913,-2663.449219,-2662.760498,-2712.144531
22,150,"(300, 300)","(300, 300)",1113484,184.94112348556519,-2677.857422,-2677.220947,-2727.736084
30,150,"(600, 600)","(600, 600)",2765884,165.7949800491333,-2713.655518,-2714.104492,-2760.452881
29,100,"(600, 600)","(600, 600)",2675784,148.91386675834656,-2758.453857,-2758.238037,-2813.320801
31,200,"(600, 600)","(600, 600)",2855984,152.55498814582825,-2786.570068,-2786.233154,-2829.288818
13,100,"(100, 100)","(100, 100)",296784,342.01922249794006,-3125.816895,-3127.983643,-3202.745850
15,200,"(100, 100)","(100, 100)",326984,326.05582427978516,-3155.004883,-3154.033691,-3235.172852
14,150,"(100, 100)","(100, 100)",311884,271.4332835674286,-3276.206787,-3274.327637,-3367.392090
28,50,"(600, 600)","(600, 600)",2585684,177.94503617286682,-3371.299316,-3372.724121,-3437.377686
20,50,"(300, 300)","(300, 300)",1023284,188.02404117584229,-3360.594482,-3360.540283,-3437.879150
12,50,"(100, 100)","(100, 100)",281684,314.9308421611786,-3508.988281,-3509.805908,-3620.001709
19,25,"(300, 300)","(300, 300)",1000734,179.56019496917725,-4810.242188,-4809.285645,-4935.563965
27,25,"(600, 600)","(600, 600)",2540634,128.81315517425537,-4840.285156,-4840.305664,-4948.560059
11,25,"(100, 100)","(100, 100)",274134,388.0813310146332,-5354.678223,-5354.369629,-5547.478027
7,200,"(30, 30)","(30, 30)",92624,487.64377331733704,-7948.089844,-7945.155762,-8231.082031
6,150,"(30, 30)","(30, 30)",88024,506.62707805633545,-8092.123047,-8086.749023,-8377.909180
3,25,"(30, 30)","(30, 30)",76524,506.0528028011322,-8235.633789,-8233.548828,-8467.667969
5,100,"(30, 30)","(30, 30)",83424,453.6379098892212,-8226.747070,-8227.949219,-8497.263672
4,50,"(30, 30)","(30, 30)",78824,572.3717362880707,-8306.811523,-8305.619141,-8590.480469
26,5,"(600, 600)","(600, 600)",2504594,134.57432413101196,-15040.546875,-15035.153320,-15009.952148
18,5,"(300, 300)","(300, 300)",982694,144.07291507720947,-15228.252930,-15227.082031,-15196.536133
10,5,"(100, 100)","(100, 100)",268094,240.08068084716797,-16117.431641,-16124.436523,-16128.195312
2,5,"(30, 30)","(30, 30)",74684,427.6548056602478,-17896.361328,-17894.347656,-18030.552734
17,2,"(300, 300)","(300, 300)",979988,155.93494153022766,-23126.660156,-23167.031250,-23104.582031
25,2,"(600, 600)","(600, 600)",2499188,147.17906403541565,-23043.591797,-23069.128906,-23139.789062
9,2,"(100, 100)","(100, 100)",267188,220.77272510528564,-23694.003906,-23673.738281,-23727.613281
1,2,"(30, 30)","(30, 30)",74408,367.1143264770508,-24693.566406,-24693.535156,-24771.154297
16,1,"(300, 300)","(300, 300)",979086,212.65065908432007,-27269.273438,-27269.359375,-27314.341797
24,1,"(600, 600)","(600, 600)",2497386,222.35293412208557,-27675.376953,-27662.066406,-27608.921875
8,1,"(100, 100)","(100, 100)",266886,280.9245111942291,-27966.160156,-27982.490234,-27959.251953
0,1,"(30, 30)","(30, 30)",74316,494.00297594070435,-28742.960938,-28736.472656,-28804.677734

In [62]:
df = compile_attributes("iwae", "svhn_perturbed")
df.sort_values("max_validation", ascending=False)

0 iwae/svhn_perturbed/-1/1557256067/attributes.pk
1 iwae/svhn_perturbed/-1/1557256224/attributes.pk
2 iwae/svhn_perturbed/-1/1557256567/attributes.pk
3 iwae/svhn_perturbed/-1/1557256875/attributes.pk
4 iwae/svhn_perturbed/-1/1557257571/attributes.pk
5 iwae/svhn_perturbed/-1/1557258008/attributes.pk
6 iwae/svhn_perturbed/-1/1557258585/attributes.pk
7 iwae/svhn_perturbed/-1/1557259090/attributes.pk
8 iwae/svhn_perturbed/-1/1557259668/attributes.pk
9 iwae/svhn_perturbed/-1/1557259836/attributes.pk
10 iwae/svhn_perturbed/-1/1557260055/attributes.pk
11 iwae/svhn_perturbed/-1/1557260406/attributes.pk
12 iwae/svhn_perturbed/-1/1557260603/attributes.pk
13 iwae/svhn_perturbed/-1/1557261193/attributes.pk
14 iwae/svhn_perturbed/-1/1557261715/attributes.pk
15 iwae/svhn_perturbed/-1/1557262091/attributes.pk
16 iwae/svhn_perturbed/-1/1557262649/attributes.pk
17 iwae/svhn_perturbed/-1/1557262882/attributes.pk
18 iwae/svhn_perturbed/-1/1557263049/attributes.pk
19 iwae/svhn_perturbed/-1/1557263283/attributes.pk
20 iwae/svhn_perturbed/-1/1557263507/attributes.pk
21 iwae/svhn_perturbed/-1/1557263752/attributes.pk
22 iwae/svhn_perturbed/-1/1557264226/attributes.pk
23 iwae/svhn_perturbed/-1/1557264604/attributes.pk
24 iwae/svhn_perturbed/-1/1557265149/attributes.pk
25 iwae/svhn_perturbed/-1/1557265449/attributes.pk
26 iwae/svhn_perturbed/-1/1557265820/attributes.pk
27 iwae/svhn_perturbed/-1/1557266032/attributes.pk
28 iwae/svhn_perturbed/-1/1557266268/attributes.pk
29 iwae/svhn_perturbed/-1/1557266570/attributes.pk
30 iwae/svhn_perturbed/-1/1557266921/attributes.pk
31 iwae/svhn_perturbed/-1/1557267293/attributes.pk
Found 32 attributes
17

,nz,nnodes_recog,nnodes_gener,num_weights,wall_time,test_ll,test_curve,max_validation
21,100,"(300, 300)","(300, 300)",1713448,470.0805022716522,1390.509521,1390.485229,1187.829590
23,200,"(300, 300)","(300, 300)",1833648,540.7205533981323,1383.857422,1384.115234,1184.234009
22,150,"(300, 300)","(300, 300)",1773548,373.73898911476135,1367.865112,1367.396240,1174.612305
28,50,"(600, 600)","(600, 600)",4024548,297.23629927635193,1327.431885,1327.197876,1132.771118
20,50,"(300, 300)","(300, 300)",1653348,241.03086066246033,1327.151489,1327.191406,1130.661499
29,100,"(600, 600)","(600, 600)",4144648,346.73462080955505,1319.976318,1320.099609,1122.400879
30,150,"(600, 600)","(600, 600)",4264748,368.53119444847107,1296.923462,1297.447754,1101.125244
31,200,"(600, 600)","(600, 600)",4384848,474.0469207763672,1303.728149,1303.624634,1100.323730
15,200,"(100, 100)","(100, 100)",532848,553.9164371490479,1258.915894,1259.264526,1067.578369
12,50,"(100, 100)","(100, 100)",472548,586.0756597518921,1248.650635,1249.021973,1060.592041
13,100,"(100, 100)","(100, 100)",492648,517.9095871448517,1234.763672,1234.643677,1046.213013
14,150,"(100, 100)","(100, 100)",512748,371.67039465904236,1209.765381,1209.745728,1020.319580
27,25,"(600, 600)","(600, 600)",3964498,231.9465000629425,1063.527466,1063.586792,893.074463
19,25,"(300, 300)","(300, 300)",1623298,220.3731918334961,1063.318359,1062.900757,889.645874
11,25,"(100, 100)","(100, 100)",462498,193.6615173816681,985.964905,985.830078,814.538574
3,25,"(30, 30)","(30, 30)",131818,692.3742771148682,845.820984,846.046814,686.423279
5,100,"(30, 30)","(30, 30)",140968,573.4752578735352,824.640747,824.764160,665.557800
7,200,"(30, 30)","(30, 30)",153168,574.3486270904541,799.092407,799.187073,644.535950
4,50,"(30, 30)","(30, 30)",134868,432.9972240924835,791.829163,791.679382,639.230225
6,150,"(30, 30)","(30, 30)",147068,500.90269017219543,780.414307,780.305176,631.713196
18,5,"(300, 300)","(300, 300)",1599258,229.87131762504578,525.975464,525.825134,409.275513
10,5,"(100, 100)","(100, 100)",454458,346.5824854373932,518.340454,518.186523,402.525726
26,5,"(600, 600)","(600, 600)",3916458,208.21320986747742,516.039307,516.174194,401.810852
2,5,"(30, 30)","(30, 30)",129378,303.0950071811676,471.510132,471.979950,368.752350
25,2,"(600, 600)","(600, 600)",3909252,367.4068126678467,346.410492,346.412811,252.796661
9,2,"(100, 100)","(100, 100)",453252,214.886381149292,342.272675,342.227753,247.623657
17,2,"(300, 300)","(300, 300)",1595652,163.44242882728577,339.969086,340.269928,246.664917
1,2,"(30, 30)","(30, 30)",129012,339.0152385234833,330.021240,330.254120,235.776749
8,1,"(100, 100)","(100, 100)",452850,164.28685092926025,175.116898,176.108810,124.431862
16,1,"(300, 300)","(300, 300)",1594450,229.0047845840454,178.682175,177.490417,124.089233
24,1,"(600, 600)","(600, 600)",3906850,295.83426785469055,178.081436,177.745346,123.139259
0,1,"(30, 30)","(30, 30)",128890,153.20049262046814,143.070816,143.082031,89.764748

In [63]:
df = compile_attributes("iwae", "svhn_discrete")
df.sort_values("max_validation", ascending=False)

0 iwae/svhn_discrete/-1/1557267771/attributes.pk
1 iwae/svhn_discrete/-1/1557267970/attributes.pk
2 iwae/svhn_discrete/-1/1557268178/attributes.pk
3 iwae/svhn_discrete/-1/1557268958/attributes.pk
4 iwae/svhn_discrete/-1/1557269731/attributes.pk
5 iwae/svhn_discrete/-1/1557270235/attributes.pk
6 iwae/svhn_discrete/-1/1557271009/attributes.pk
7 iwae/svhn_discrete/-1/1557271591/attributes.pk
8 iwae/svhn_discrete/-1/1557272245/attributes.pk
9 iwae/svhn_discrete/-1/1557272469/attributes.pk
10 iwae/svhn_discrete/-1/1557272657/attributes.pk
11 iwae/svhn_discrete/-1/1557272935/attributes.pk
12 iwae/svhn_discrete/-1/1557273080/attributes.pk
13 iwae/svhn_discrete/-1/1557273572/attributes.pk
14 iwae/svhn_discrete/-1/1557273971/attributes.pk
15 iwae/svhn_discrete/-1/1557274260/attributes.pk
16 iwae/svhn_discrete/-1/1557274681/attributes.pk
17 iwae/svhn_discrete/-1/1557274922/attributes.pk
18 iwae/svhn_discrete/-1/1557275097/attributes.pk
19 iwae/svhn_discrete/-1/1557275351/attributes.pk
20 iwae/svhn_discrete/-1/1557275625/attributes.pk
21 iwae/svhn_discrete/-1/1557275824/attributes.pk
22 iwae/svhn_discrete/-1/1557276192/attributes.pk
23 iwae/svhn_discrete/-1/1557276351/attributes.pk
24 iwae/svhn_discrete/-1/1557276699/attributes.pk
25 iwae/svhn_discrete/-1/1557276902/attributes.pk
26 iwae/svhn_discrete/-1/1557277133/attributes.pk
27 iwae/svhn_discrete/-1/1557277421/attributes.pk
28 iwae/svhn_discrete/-1/1557277649/attributes.pk
29 iwae/svhn_discrete/-1/1557277937/attributes.pk
30 iwae/svhn_discrete/-1/1557278447/attributes.pk
31 iwae/svhn_discrete/-1/1557278846/attributes.pk
Found 32 attributes
15

,nz,nnodes_recog,nnodes_gener,num_weights,wall_time,test_ll,test_curve,max_validation
29,100,"(600, 600)","(600, 600)",3108024,506.29507994651794,-4886.108887,-4886.273926,-5450.383301
30,150,"(600, 600)","(600, 600)",3198124,395.0633466243744,-4958.350098,-4958.024414,-5463.157227
31,200,"(600, 600)","(600, 600)",3288224,520.2928411960602,-4979.341309,-4979.489746,-5469.005371
21,100,"(300, 300)","(300, 300)",1284624,363.59100222587585,-5086.898438,-5087.619141,-5655.905273
23,200,"(300, 300)","(300, 300)",1374824,344.18911385536194,-5185.862305,-5186.444824,-5682.322266
22,150,"(300, 300)","(300, 300)",1329724,155.98754501342773,-5709.486328,-5709.363281,-6417.045410
13,100,"(100, 100)","(100, 100)",369024,395.19485998153687,-6115.921387,-6116.144531,-7081.476562
15,200,"(100, 100)","(100, 100)",399224,417.71331763267517,-6238.813965,-6238.878906,-7243.536621
28,50,"(600, 600)","(600, 600)",3017924,284.5267174243927,-6486.936035,-6486.773926,-7712.530273
14,150,"(100, 100)","(100, 100)",384124,284.93070673942566,-6627.502930,-6626.529785,-7765.933594
20,50,"(300, 300)","(300, 300)",1239524,195.44096446037292,-6733.380371,-6733.360840,-8018.677734
12,50,"(100, 100)","(100, 100)",353924,488.12256121635437,-6727.917480,-6727.934082,-8070.856934
27,25,"(600, 600)","(600, 600)",2972874,224.07813262939453,-9783.657227,-9784.447266,-11895.980469
19,25,"(300, 300)","(300, 300)",1216974,270.078652381897,-9786.255859,-9786.944336,-11954.075195
11,25,"(100, 100)","(100, 100)",346374,141.62657046318054,-10562.151367,-10561.960938,-12997.088867
7,200,"(30, 30)","(30, 30)",114464,649.9011285305023,-11149.987305,-11149.794922,-13641.258789
6,150,"(30, 30)","(30, 30)",109864,578.6307969093323,-11401.276367,-11400.594727,-13977.284180
5,100,"(30, 30)","(30, 30)",105264,769.9480755329132,-11467.740234,-11469.172852,-14058.346680
3,25,"(30, 30)","(30, 30)",98364,769.4318156242371,-11608.090820,-11608.789062,-14210.418945
4,50,"(30, 30)","(30, 30)",100664,500.08875608444214,-11664.057617,-11664.580078,-14317.192383
26,5,"(600, 600)","(600, 600)",2936834,284.123877286911,-21657.390625,-21657.025391,-24769.691406
18,5,"(300, 300)","(300, 300)",1198934,250.86986327171326,-21680.419922,-21679.208984,-24813.964844
10,5,"(100, 100)","(100, 100)",340334,273.98781871795654,-21667.154297,-21661.625000,-24925.742188
2,5,"(30, 30)","(30, 30)",96524,776.755065202713,-22167.027344,-22173.550781,-25370.556641
17,2,"(300, 300)","(300, 300)",1196228,171.1107680797577,-27705.484375,-27715.683594,-30881.179688
25,2,"(600, 600)","(600, 600)",2931428,227.35092043876648,-27843.246094,-27836.037109,-30965.169922
9,2,"(100, 100)","(100, 100)",339428,184.52509570121765,-27723.855469,-27722.974609,-31007.306641
1,2,"(30, 30)","(30, 30)",96248,204.29070568084717,-28388.367188,-28392.285156,-31581.236328
16,1,"(300, 300)","(300, 300)",1195326,237.1517369747162,-32609.568359,-32549.654297,-35199.636719
24,1,"(600, 600)","(600, 600)",2929626,199.21395230293274,-33163.636719,-33146.816406,-35516.308594
8,1,"(100, 100)","(100, 100)",339126,220.72328543663025,-32982.941406,-32993.734375,-35543.726562
0,1,"(30, 30)","(30, 30)",96156,189.8568766117096,-34268.718750,-34286.378906,-36506.742188

In [64]:
df = compile_attributes("iwae", "cifar10_perturbed")
df.sort_values("max_validation", ascending=False)

0 iwae/cifar10_perturbed/-1/1557496887/attributes.pk
1 iwae/cifar10_perturbed/-1/1557496976/attributes.pk
2 iwae/cifar10_perturbed/-1/1557497247/attributes.pk
3 iwae/cifar10_perturbed/-1/1557497444/attributes.pk
4 iwae/cifar10_perturbed/-1/1557497605/attributes.pk
5 iwae/cifar10_perturbed/-1/1557497826/attributes.pk
6 iwae/cifar10_perturbed/-1/1557498022/attributes.pk
7 iwae/cifar10_perturbed/-1/1557498256/attributes.pk
8 iwae/cifar10_perturbed/-1/1557498483/attributes.pk
9 iwae/cifar10_perturbed/-1/1557498587/attributes.pk
10 iwae/cifar10_perturbed/-1/1557498727/attributes.pk
11 iwae/cifar10_perturbed/-1/1557498824/attributes.pk
12 iwae/cifar10_perturbed/-1/1557498953/attributes.pk
13 iwae/cifar10_perturbed/-1/1557499112/attributes.pk
14 iwae/cifar10_perturbed/-1/1557499351/attributes.pk
15 iwae/cifar10_perturbed/-1/1557499600/attributes.pk
16 iwae/cifar10_perturbed/-1/1557499801/attributes.pk
17 iwae/cifar10_perturbed/-1/1557499898/attributes.pk
18 iwae/cifar10_perturbed/-1/1557499985/attributes.pk
19 iwae/cifar10_perturbed/-1/1557500081/attributes.pk
20 iwae/cifar10_perturbed/-1/1557500179/attributes.pk
21 iwae/cifar10_perturbed/-1/1557500325/attributes.pk
22 iwae/cifar10_perturbed/-1/1557500470/attributes.pk
23 iwae/cifar10_perturbed/-1/1557500666/attributes.pk
24 iwae/cifar10_perturbed/-1/1557500852/attributes.pk
25 iwae/cifar10_perturbed/-1/1557500924/attributes.pk
26 iwae/cifar10_perturbed/-1/1557501022/attributes.pk
27 iwae/cifar10_perturbed/-1/1557501121/attributes.pk
28 iwae/cifar10_perturbed/-1/1557501263/attributes.pk
Found 29 attributes
13

,nz,nnodes_recog,nnodes_gener,num_weights,wall_time,test_ll,test_curve,max_validation
20,50,"(300, 300)","(300, 300)",1653348,144.41545224189758,829.775391,829.590637,826.861084
22,150,"(300, 300)","(300, 300)",1773548,194.20105409622192,812.812378,812.008728,810.620239
23,200,"(300, 300)","(300, 300)",1833648,171.93837881088257,804.135681,803.596497,800.237183
21,100,"(300, 300)","(300, 300)",1713448,142.23358821868896,800.754883,801.357605,798.604919
25,50,"(600, 600)","(600, 600)",4024548,95.67063999176025,793.495972,793.447510,789.351013
13,100,"(100, 100)","(100, 100)",492648,236.5419797897339,785.756470,786.930664,783.378174
14,150,"(100, 100)","(100, 100)",512748,246.77867650985718,783.265503,782.698303,780.644653
27,150,"(600, 600)","(600, 600)",4264748,140.29681944847107,773.835144,773.980713,770.533325
15,200,"(100, 100)","(100, 100)",532848,198.45973134040833,771.823730,772.414734,768.634277
28,200,"(600, 600)","(600, 600)",4384848,146.21987557411194,769.752930,768.932190,765.881775
26,100,"(600, 600)","(600, 600)",4144648,96.34164929389954,765.208130,764.907898,762.322815
12,50,"(100, 100)","(100, 100)",472548,156.8084466457367,755.506653,756.252197,754.847656
19,25,"(300, 300)","(300, 300)",1623298,95.5805823802948,747.690674,747.040710,744.941895
24,25,"(600, 600)","(600, 600)",3964498,69.95807695388794,738.105591,737.933167,736.248474
11,25,"(100, 100)","(100, 100)",462498,127.1230149269104,713.518921,712.973267,712.633484
6,150,"(30, 30)","(30, 30)",147068,232.23895454406738,601.336670,601.446594,599.640381
7,200,"(30, 30)","(30, 30)",153168,225.22449946403503,597.799072,598.777100,597.223938
5,100,"(30, 30)","(30, 30)",140968,193.6176826953888,588.125793,588.501709,585.856873
4,50,"(30, 30)","(30, 30)",134868,218.3992519378662,586.801575,586.126892,585.216003
3,25,"(30, 30)","(30, 30)",131818,158.98523926734924,548.018921,548.473816,547.124084
18,5,"(300, 300)","(300, 300)",1599258,93.37569499015808,398.500092,398.306488,396.920319
10,5,"(100, 100)","(100, 100)",454458,94.56318664550781,392.831909,392.835938,390.668060
2,5,"(30, 30)","(30, 30)",129378,194.93512964248657,377.340118,376.768250,374.773529
9,2,"(100, 100)","(100, 100)",453252,138.72342085838318,239.599457,239.416107,238.272095
17,2,"(300, 300)","(300, 300)",1595652,85.62644243240356,235.958801,236.049652,233.363876
1,2,"(30, 30)","(30, 30)",129012,269.0368101596832,228.403122,228.354752,224.882080
16,1,"(300, 300)","(300, 300)",1594450,94.65209245681763,141.213791,141.339081,138.960419
8,1,"(100, 100)","(100, 100)",452850,101.35727453231812,125.622574,125.410149,124.087151
0,1,"(30, 30)","(30, 30)",128890,79.91194128990173,115.488113,116.069115,113.089737

In [65]:
df = compile_attributes("iwae", "cifar10_discrete")
df.sort_values("max_validation", ascending=False)

0 iwae/cifar10_discrete/-1/1557501411/attributes.pk
1 iwae/cifar10_discrete/-1/1557501655/attributes.pk
2 iwae/cifar10_discrete/-1/1557515076/attributes.pk
3 iwae/cifar10_discrete/-1/1557515311/attributes.pk
4 iwae/cifar10_discrete/-1/1557515640/attributes.pk
5 iwae/cifar10_discrete/-1/1557515943/attributes.pk
6 iwae/cifar10_discrete/-1/1557516186/attributes.pk
7 iwae/cifar10_discrete/-1/1557516433/attributes.pk
8 iwae/cifar10_discrete/-1/1557516645/attributes.pk
9 iwae/cifar10_discrete/-1/1557516885/attributes.pk
10 iwae/cifar10_discrete/-1/1557516996/attributes.pk
11 iwae/cifar10_discrete/-1/1557517159/attributes.pk
12 iwae/cifar10_discrete/-1/1557517290/attributes.pk
13 iwae/cifar10_discrete/-1/1557517518/attributes.pk
14 iwae/cifar10_discrete/-1/1557517666/attributes.pk
15 iwae/cifar10_discrete/-1/1557517896/attributes.pk
16 iwae/cifar10_discrete/-1/1557518104/attributes.pk
17 iwae/cifar10_discrete/-1/1557518243/attributes.pk
18 iwae/cifar10_discrete/-1/1557518357/attributes.pk
19 iwae/cifar10_discrete/-1/1557518458/attributes.pk
20 iwae/cifar10_discrete/-1/1557518630/attributes.pk
21 iwae/cifar10_discrete/-1/1557518852/attributes.pk
22 iwae/cifar10_discrete/-1/1557519012/attributes.pk
23 iwae/cifar10_discrete/-1/1557519134/attributes.pk
24 iwae/cifar10_discrete/-1/1557519228/attributes.pk
25 iwae/cifar10_discrete/-1/1557519358/attributes.pk
26 iwae/cifar10_discrete/-1/1557519570/attributes.pk
Found 27 attributes
10

,nz,nnodes_recog,nnodes_gener,num_weights,wall_time,test_ll,test_curve,max_validation
26,200,"(600, 600)","(600, 600)",3288224,204.3881938457489,-7230.870605,-7230.706543,-7252.034180
25,150,"(600, 600)","(600, 600)",3198124,210.1119842529297,-7407.052734,-7407.745605,-7426.002441
20,200,"(300, 300)","(300, 300)",1374824,219.98974633216858,-7428.555176,-7427.566406,-7453.630371
24,100,"(600, 600)","(600, 600)",3108024,128.17688131332397,-8261.233398,-8261.506836,-8281.622070
15,200,"(100, 100)","(100, 100)",399224,206.34545421600342,-9593.081055,-9592.827148,-9619.293945
14,150,"(100, 100)","(100, 100)",384124,228.44155955314636,-9604.997070,-9605.527344,-9629.405273
13,100,"(100, 100)","(100, 100)",369024,146.37451601028442,-10161.250977,-10163.278320,-10186.875977
19,50,"(300, 300)","(300, 300)",1239524,152.3418447971344,-10324.374023,-10324.935547,-10342.405273
23,50,"(600, 600)","(600, 600)",3017924,91.61871242523193,-10402.959961,-10403.004883,-10421.077148
12,50,"(100, 100)","(100, 100)",353924,225.81939435005188,-10488.030273,-10487.264648,-10509.992188
18,25,"(300, 300)","(300, 300)",1216974,99.24300003051758,-13327.644531,-13327.718750,-13321.097656
11,25,"(100, 100)","(100, 100)",346374,129.19799160957336,-13511.468750,-13512.002930,-13507.809570
7,150,"(30, 30)","(30, 30)",109864,210.33630800247192,-14371.180664,-14374.435547,-14341.473633
5,50,"(30, 30)","(30, 30)",100664,240.40513134002686,-14600.947266,-14600.150391,-14564.953125
4,25,"(30, 30)","(30, 30)",98364,301.28868985176086,-14763.648438,-14761.638672,-14729.378906
8,200,"(30, 30)","(30, 30)",114464,238.0643494129181,-14853.233398,-14852.781250,-14819.636719
6,100,"(30, 30)","(30, 30)",105264,245.19254899024963,-15124.621094,-15125.546875,-15109.638672
10,5,"(100, 100)","(100, 100)",340334,161.22746229171753,-22282.681641,-22285.076172,-22343.064453
17,5,"(300, 300)","(300, 300)",1198934,112.64744329452515,-22395.875000,-22405.746094,-22416.203125
22,5,"(600, 600)","(600, 600)",2936834,116.45867705345154,-22386.755859,-22395.472656,-22439.199219
3,5,"(30, 30)","(30, 30)",96524,327.1429030895233,-22663.468750,-22647.839844,-22669.234375
21,2,"(600, 600)","(600, 600)",2931428,158.44483470916748,-27794.054688,-27788.863281,-27832.496094
16,2,"(300, 300)","(300, 300)",1196228,136.49716138839722,-27866.896484,-27873.919922,-27977.703125
9,2,"(100, 100)","(100, 100)",339428,108.26190304756165,-28142.531250,-28178.406250,-28240.615234
2,2,"(30, 30)","(30, 30)",96248,232.02209901809692,-28191.980469,-28204.736328,-28296.677734
1,2,"(30, 30)","(30, 30)",96248,121.83634543418884,-28502.054688,-28511.763672,-28610.316406
0,1,"(30, 30)","(30, 30)",96156,237.8412628173828,-31818.460938,-31810.349609,-31820.314453